taglib.lo: /home/tso/taglib-php/php-5.6.7/ext/taglib/taglib.cpp
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/home/tso/taglib-php/php-5.6.7/ext/taglib $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /home/tso/taglib-php/php-5.6.7/ext/taglib/taglib.cpp -o taglib.lo 
$(phplibdir)/taglib.la: ./taglib.la
	$(LIBTOOL) --mode=install cp ./taglib.la $(phplibdir)

./taglib.la: $(shared_objects_taglib) $(TAGLIB_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_taglib) $(TAGLIB_SHARED_LIBADD)

